# -*- mode: ruby -*-
# vi: set ft=ruby :

USERNAME = "pcunha"

CONTROL_PLANE_NAME = USERNAME + "S"
CONTROL_PLANE_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 2048
    libvirt.default_prefix = ""
    libvirt.driver = "kvm"
  end

  config.vm.define CONTROL_PLANE_NAME do |control_plane|
    control_plane.vm.hostname = CONTROL_PLANE_NAME
    control_plane.vm.network "private_network", ip: CONTROL_PLANE_IP
    control_plane.vm.provision "ansible" do |ansible|
      ansible.playbook = "confs/playbook.yml"
      ansible.verbose = "v"
      ansible.limit = "all"
      ansible.groups = {
        "k3s" => [CONTROL_PLANE_NAME],
      }
      ansible.extra_vars = {
        k3s_server: CONTROL_PLANE_NAME,
      }
    end
  end
end
