# -*- mode: ruby -*-
# vi: set ft=ruby :

USERNAME = "aroque"

CONTROL_PLANE_NAME = USERNAME + "S"
CONTROL_PLANE_IP = "192.168.56.110"

NODE_NAME = USERNAME + "SW"
NODE_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
    libvirt.default_prefix = ""
    libvirt.driver = "kvm"
  end

  config.vm.define CONTROL_PLANE_NAME do |control_plane|
    control_plane.vm.hostname = CONTROL_PLANE_NAME
    control_plane.vm.network "private_network", ip: CONTROL_PLANE_IP
  end

  config.vm.define NODE_NAME do |node|
    node.vm.hostname = NODE_NAME
    node.vm.network "private_network", ip: NODE_IP
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "confs/playbook.yml"
      ansible.verbose = "v"
      ansible.limit = "all"
      ansible.groups = {
        "k3s" => [CONTROL_PLANE_NAME, NODE_NAME],
        "k3s_server" => [CONTROL_PLANE_NAME],
        "k3s_agent" => [NODE_NAME],
      }
      ansible.extra_vars = {
        k3s_server: CONTROL_PLANE_NAME,
        k3s_agent: NODE_NAME,
      }
    end
  end

end
